### ISSUE TITLE
Test the db status on load, but work (in a degraded state) even without it

### ISSUE THREAD

**Issue by LoicBrassart** [WildCodeSchool/create-js-monorepo#10]
Expected: 
- If the `.env` file is absent:
  - the backend starts as intended
  - (a warning could be issued, saying something like "No .env file found: routes using models won't work as intended")
  - routes not using models work as usual
  - routes using models fail "gracefully" (is there a specific HTTP code for this kind of thing ?)
- If the `.env` file is present:
  - everything works as intended

Ideas:
- In the build phase, maybe check for a specific flag in the .env: if it's there, everything is fine ; otherwise model methods throw an error and controllers send a specific http code ?

**Comment by rocambille** [comment]
here is a proposition #12 : getting a connection from the pool on start, catch errors, and output a warning in console. this addresses the "no .env detection".

IMHO the http status 500 is adapted here: it's a server error if a route relies on models while they are not available

**Comment by LoicBrassart** [comment]
Fine by me, topic closed!
