### ISSUE TITLE
ESLint/Prettier check every file on commit, instead of *changed* files

### ISSUE THREAD

**Issue by LoicBrassart** [WildCodeSchool/create-js-monorepo#11]
Everything's in the title :p

It makes checks longer and triggers unwanted effects in edgecases (ie: commit once with the `--ignore-checks` flag, but the next commit will re-trigger an error)

**Comment by rocambille** [comment]
to go further, is there any way to check on add instead of commit? often we add files, do a commit which fails, fix the errors and commit again without adding : the checks passes while the commit is incomplete

**Comment by LoicBrassart** [comment]
@rocambille I just checked and found nothing about pre-add hooks, so I'm not sure it's feasible (I may be wrong though :shrug: )

**Comment by LoicBrassart** [comment]
- :heavy_check_mark: I've tried (and managed!) to call prettier/eslint only on staged files by updating the Husky hook.
  - :wrench: To do so I had to move prettier/eslint packages to the global `package.json`
- :x: On my current branch, rules have to be consistent for every tested file -> We can't use basic rules for the backend and react-specific for the frontend

I'll stop working on this one for now by lack of time, but please notify me if you need input on what I did :(
