### ISSUE TITLE
⚠️ npm build

### ISSUE THREAD

**Issue by GorskiAnthony** [WildCodeSchool/create-js-monorepo#124]
Hello 👋
It seems that the `npm build` command doesn't work. 
The keyword `run` is missing.

```diff
- npm build
+ npm run build
```

[npm-run-script | npm Docs](https://docs.npmjs.com/cli/v10/commands/npm-run-script#ignore-scripts)

https://github.com/WildCodeSchool/js-template-fullstack/blob/6556a185a5ccb1666e50927e853b210db57afad9/docker-entry.sh#L4

**Comment by rocambille** [comment]
solved by #121
