### ISSUE TITLE
impossible to install

### ISSUE THREAD

**Issue by brrrrrbrrrr** [WildCodeSchool/create-js-monorepo#155]
Hello, I wanted to install it and :
![harmonia-crash](https://github.com/WildCodeSchool/create-harmonia/assets/114990937/b9b4e0f9-c671-43e4-8abb-09e49e1be6ce)

**Comment by rocambille** [comment]
Looks like node.js has some issues with slashes in git bash. You should try in a VS Code terminal :)

Source: https://stackoverflow.com/questions/76350143/how-can-i-fix-err-tty-init-failed-when-initializing-tty-in-a-node-js-git-bash-en

**Comment by brrrrrbrrrr** [comment]
Thank you :) i will try
