### ISSUE TITLE
Import order linter errors in server config.js

### ISSUE THREAD

**Issue by Acetoshi** [WildCodeSchool/create-js-monorepo#156]
Linter gives imports order error when uncommenting line 111, conflicts with line 87.

i suggest to swap them, is it ok if i open a PR ? 

![image](https://github.com/WildCodeSchool/create-harmonia/assets/23642571/648de14f-c9cd-4acd-90e2-eadac7dbb6c5)

**Comment by Acetoshi** [comment]
EDIT : swapping them won't work.  `const path = require("path");`  needs to be put at the top of the document.

**Comment by rocambille** [comment]
Next major release will use [Biome](https://biomejs.dev/) to replace ESLint and Prettier. This import order is compatible with Biome: that will fix the issue :slightly_smiling_face:
