### ISSUE TITLE
Nom du fichier gitignore dans le template

### ISSUE THREAD

**Issue by jujuck** [WildCodeSchool/create-js-monorepo#158]
Le nom du fichier gitignore n'est correcte, il n'y a pas le point avant ".gitignore"

**Comment by rocambille** [comment]
C'est volontaire :)

Les fichiers .gitignore ne sont pas inclus à la publication d'un package npm. Le fichier est renommé dans le script de création de projet.

https://github.com/WildCodeSchool/create-js-monorepo/blob/main/bin/create-js-monorepo.js#L127
