### ISSUE TITLE
typescript version of backend ?

### ISSUE THREAD

**Issue by gnos28** [WildCodeSchool/create-js-monorepo#32]
this is more a question than an issue

I'm currently trying to convert this great template to typescript (only the backend part though)
but currently not skilled enough to do something like a dynamic typing which browse for files in "models" subfolder and create some kind of a big typed object containing instances of all tables + basic & custom crud methods inside of each instances

I don't even know if that's possible with typescript, has anyone already done this ?

**Comment by rocambille** [comment]
Late, but done :)
