### ISSUE TITLE
Implement an auto-loading mechanism in front's main folders

### ISSUE THREAD

**Issue by LoicBrassart** [WildCodeSchool/create-js-monorepo#9]
The idea would be to import our pages with something like `import {HomePage, CharactersPage, CarsPage} from @pages` 
- The "manual" way to do it would be to add an `index.js` in every main folder (@pages, @components, @services, @assets) and to import everything the old-fashioned way (one line per import), then to export everything from this index
  - Cons: it's a pain to maintain
  - Pros: it works :shrug: 
- The "automated" way would be to take inspiration from what's done in the main folders in the backend: read the folders's content, import every component one by one and export it all at the end
  - Cons: it's not implemented ("yet" ? Pretty please ?) ; some trainers may have a different file architecture
  - Pros: no maintenance, it just works, and imports are way easier in the whole React project

**Comment by rocambille** [comment]
following unsuccessful attempts, I propose to close this one?

**Comment by LoicBrassart** [comment]
Eeyup, I won't be able to make progress on this one either
