### ISSUE TITLE
Can't init this template

### ISSUE THREAD

**Issue by brrrrrbrrrr** [WildCodeSchool/create-js-monorepo#99]
Hello ! 
I want to use this template for a personal project (which I already used during my training), but I can't initialize it,
after npm install, modifications are made in the three yarn.lock files,
and when I do git add . and git commit -m, I get this message:
![bug](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/e82209d8-f98b-49e1-9ff5-b4edf8ab7915)
I tried the suggestion but it doesn't work either
Thank's :)

**Comment by rocambille** [comment]
try `git restore --staged <files>` ;)

(with <files> being the list of your lock files to unstage)

**Comment by brrrrrbrrrr** [comment]
I tried, it still doesn't work
![bug_staged](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/0c9db3e3-8fe1-49ca-9bb1-1c994b6ffdc5)
![bug_3](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/a32907c0-fbd7-4e68-bec8-463c20fdb595)

**Comment by rocambille** [comment]
what is the result of `git status` ?

**Comment by brrrrrbrrrr** [comment]
Here is what I have with a git status
![status](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/1b106030-59c8-46a0-84b9-94abfcd1cd52)

**Comment by Gwada** [comment]
I have the same problem. Why use npm, yarn and pnpm together? this is bad practice we have to use a single package manager especially since the husky program blocks commits [doc](https://www.reddit.com/r/node/comments/quwq1x/why_are_yarnlock_and_packagelockjson_updated/)

**Comment by rocambille** [comment]
@brrrrrbrrrr there we go : you didn't unstaged yarn.lock

Looking at your previous message, it's useless to unstaged the file with `git restore --staged` if you stage it again with a `git add .` in the next line...

Just unstage the file and do the commit

**Comment by brrrrrbrrrr** [comment]
I tried both options, my git status was not done at the right time in my previous message.
I did what you said, without the "add.", and with
![restore_1](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/4980bded-1b6d-46db-aacd-35581c325582)
![restore_2](https://github.com/WildCodeSchool/js-template-fullstack/assets/114990937/e2e6ae1f-1e3d-45d1-9a72-120aa75c8771)
